services:
  api:
    build: .
    ports:
      - "${API_HOST_PORT}:9090"
    environment:
      - DSN=postgres://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}?sslmode=${DB_SSLMODE}
      - LISTEN_PORT=${LISTEN_PORT}
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - logs-data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
  migrate:
    image: migrate/migrate
    volumes:
      - ./db/migrations/postgres:/migrations
    entrypoint: ["migrate", "-path", "/migrations", "-database", "postgres://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}?sslmode=${DB_SSLMODE}"]
    command: ["up"]
    depends_on:
      - db
  db-test:
    image: postgres:15
    environment:
      POSTGRES_USER: ${TEST_DB_USER}
      POSTGRES_PASSWORD: ${TEST_DB_PASSWORD}
      POSTGRES_DB: ${TEST_DB_NAME}
    volumes:
      - logs-data-test:/var/lib/postgresql/data
    ports:
      - "${TEST_DB_PORT}:5432"
  migrate-test:
    image: migrate/migrate
    volumes:
      - ./db/migrations/postgres:/migrations
    entrypoint: ["migrate", "-path", "/migrations", "-database", "postgres://${TEST_DB_USER}:${TEST_DB_PASSWORD}@db-test:5432/${TEST_DB_NAME}?sslmode=${TEST_DB_SSLMODE}"]
    command: ["up"]
    depends_on:
      - db-test
  db-unit-tests:
    image: postgres:15
    environment:
      POSTGRES_USER: ${UNIT_TEST_DB_USER}
      POSTGRES_PASSWORD: ${UNIT_TEST_DB_PASSWORD}
      POSTGRES_DB: ${UNIT_TEST_DB_NAME}
    volumes:
      - logs-data-unit-tests:/var/lib/postgresql/data
    ports:
      - "${UNIT_TEST_DB_PORT}:5432"

  migrate-unit-tests:
    image: migrate/migrate
    volumes:
      - ./db/migrations/postgres:/migrations
    entrypoint: ["migrate", "-path", "/migrations", "-database", "postgres://${UNIT_TEST_DB_USER}:${UNIT_TEST_DB_PASSWORD}@db-unit-tests:5432/${UNIT_TEST_DB_NAME}?sslmode=${UNIT_TEST_DB_SSLMODE}"]
    command: ["up"]
    depends_on:
      - db-unit-tests

volumes:
  logs-data:
  logs-data-test:
  logs-data-unit-tests: